{% set version = "2.10.0" %}

package:
  name: rancher-cli
  version: {{ version }}

source:
  url: https://github.com/rancher/cli/archive/v{{ version }}.tar.gz
  sha256: d44358847d6f25bb185f79cb1f8ef8b91ba644b29dc2832e593f31b98fd49765

build:
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - {{ stdlib("c") }}
    - go-licenses

test:
  requires:
    - m2-grep  # [win]
  commands:
    - rancher --help
    - rancher --version
    - rancher --version | grep -iE "^rancher version v{{ version.replace(".", "\.") }}$"

about:
  home: https://github.com/rancher/cli
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/
  summary: The Rancher Command Line Interface (CLI) is a unified tool for interacting with your Rancher Server.
  doc_url: https://ranchermanager.docs.rancher.com/reference-guides/cli-with-rancher/rancher-cli

extra:
  recipe-maintainers:
    - bollwyvl
