# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "2.13.1"

package:
  name: rancher-cli
  version: ${{ version }}

source:
  url: https://github.com/rancher/cli/archive/v${{ version }}.tar.gz
  sha256: e6893558d3168007e504e19977ec4c7e6cf58beb6c864214911b97a344b5e978

build:
  number: 0
  script:
    file: build-rancher-cli

requirements:
  build:
    - ${{ compiler("go") }}
    - ${{ stdlib("c") }}
    - go-licenses

tests:
  - requirements:
      run:
        - if: win
          then: m2-grep
    script:
      - rancher --help
      - rancher --version
      - rancher --version | grep -iE "^rancher version v${{ version | replace(".", "\\.") }}$"

about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/
  summary: The Rancher Command Line Interface (CLI) is a unified tool for interacting with your Rancher Server.
  homepage: https://github.com/rancher/cli
  documentation: https://ranchermanager.docs.rancher.com/reference-guides/cli-with-rancher/rancher-cli

extra:
  recipe-maintainers:
    - bollwyvl
